package AdventureModel.NPCs;

import AdventureModel.Player;
import AdventureModel.PowerUps.PowerUp;
import AdventureModel.Room;

import java.util.Random;

public class Dragon extends hostileNPC{
    /**
     *
     * @param name the name of the Dragon
     * @param hp the health points of the Dragon
     * @param item the Powerup carried by the Dragon
     * @param room the room the Dragon is in
     * @param text the text that the Dragon says when the player encounters it
     * @param deathText the text shown when the Dragon dies
     * @param damage the damage points of the Dragon
     */
    public Dragon(String name, double hp, PowerUp item, Room room, String text, String deathText, double damage){
        super(name, hp, item, room, text, deathText, damage);
    }

    /**
     * Reduce the health of the Dragon by Dragon.damage after being attacked by player.
     * Regenerates the health of the Dragon.
     * Returns a text with the amount of damage the player has done to the NPC.
     * @param player Player
     * @return Text indicating the damage the player has done to the NPC.
     */
    @Override
    public String fight(Player player) {
        String text = super.fight(player);
        String regenText = this.regenerate();
        text += regenText;
        return text;
    }

    /**
     * Returns the damage the Dragon deals
     * @return damage * 1/2
     */
    @Override
    public double getDamage() {
        return this.damage*1/2;
    }

    /**
     * Regenerates the Dragon
     * Returns text that indicates how much the dragon has regenerated.
     * @return Text that indicates the amount of hp the dragon has regenerated
     */
    public String regenerate(){
        Random rand = new Random();
        double min = 0;
        double regenAmount;
        if (damage>=hp){
            regenAmount = 0;
        } else{
            regenAmount = rand.nextDouble( this.damage/5 - min + 1) + min;
            this.hp += regenAmount;
        }
        String[] fullName = name.split(":");
        String firstName = fullName[0];
        if (regenAmount == 0){
            return "";
        } else return firstName + " has regenerated by " + regenAmount + "HP.\n";
    }
}
